
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author steve
 */
public class ShoppingCart extends javax.swing.JFrame {
    int itemsOrdered;       // ← sudah ada
    int totalCost;          // ← pastikan ada di sini
    String S1 = "";   


HashMap<String, Integer> itemCost = new HashMap<String, Integer>() {{
    put("One Set Soul", 50);
    put("Jeans", 60);
    put("Boots", 100);
    put("Accesories", 15);
    put("Skirt Soul", 25);
    put("Dress", 40);
}};

    /**
     * Creates new form ShoppingCart
     */
    public ShoppingCart() {
        initComponents();
        setTitle("Shopping Cart");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shoppingPane = new javax.swing.JTabbedPane();
        orderPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderLabel = new javax.swing.JLabel();
        OrderTextArea = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        orderSpinner = new javax.swing.JSpinner();
        addButton = new javax.swing.JButton();
        numberTextField = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        costTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CartPanel = new javax.swing.JPanel();
        cartPane = new javax.swing.JScrollPane();
        cartTextArea = new javax.swing.JTextArea();
        cartCostField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numberCartField = new javax.swing.JTextField();
        AddressPane = new javax.swing.JPanel();
        addressPane = new javax.swing.JScrollPane();
        AddressTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shoppingPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shoppingPaneStateChanged(evt);
            }
        });

        orderLabel.setText("Order Address:");
        orderLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 0));

        OrderTextArea.setColumns(30);
        OrderTextArea.setRows(6);
        OrderTextArea.setText("Agustav\nJl merpati \nTangerang Selatan  ");

        jLabel1.setText("Item");

        orderSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"Royal Court Attire", "Village & Tavern Wear", "Warrior & Knight Gear", "Dark Fantasy Outfits", "Elven & Mystic Robes"}));
        orderSpinner.setName(""); // NOI18N
        orderSpinner.setPreferredSize(new java.awt.Dimension(150, 25));

        addButton.setText("Add to Order ");
        addButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        numberTextField.setEditable(false);
        numberTextField.setBackground(java.awt.Color.white);
        numberTextField.setColumns(20);
        numberTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberTextField.setText(" Items Ordered: 0 ");
        numberTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        numberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextFieldActionPerformed(evt);
            }
        });

        newButton.setText("New Order");
        newButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        costTextField.setEditable(false);
        costTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Cost");

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(orderLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addComponent(OrderTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                            .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(numberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(orderSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48))
                        .addGroup(orderPanelLayout.createSequentialGroup()
                            .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exitButton))
                            .addContainerGap()))))
            .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                .addComponent(orderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addGap(12, 12, 12)
                .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(orderPanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 423, Short.MAX_VALUE)))
        );

        shoppingPane.addTab("Order Form", orderPanel);

        CartPanel.setPreferredSize(new java.awt.Dimension(250, 150));

        cartTextArea.setColumns(20);
        cartTextArea.setRows(5);
        cartTextArea.setPreferredSize(new java.awt.Dimension(250, 150));
        cartPane.setViewportView(cartTextArea);

        cartCostField.setEditable(false);
        cartCostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartCostFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Cost");

        numberCartField.setEditable(false);
        numberCartField.setBackground(java.awt.Color.white);
        numberCartField.setColumns(20);
        numberCartField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberCartField.setText(" Items Ordered: 0 ");
        numberCartField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        numberCartField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberCartFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CartPanelLayout = new javax.swing.GroupLayout(CartPanel);
        CartPanel.setLayout(CartPanelLayout);
        CartPanelLayout.setHorizontalGroup(
            CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartPanelLayout.createSequentialGroup()
                .addGroup(CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CartPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cartPane))
                    .addGroup(CartPanelLayout.createSequentialGroup()
                        .addGroup(CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CartPanelLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(numberCartField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CartPanelLayout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addGroup(CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cartCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CartPanelLayout.setVerticalGroup(
            CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(numberCartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        shoppingPane.addTab("Shopping Cart", CartPanel);

        AddressTextArea.setColumns(20);
        AddressTextArea.setRows(5);
        addressPane.setViewportView(AddressTextArea);

        javax.swing.GroupLayout AddressPaneLayout = new javax.swing.GroupLayout(AddressPane);
        AddressPane.setLayout(AddressPaneLayout);
        AddressPaneLayout.setHorizontalGroup(
            AddressPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addressPane, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );
        AddressPaneLayout.setVerticalGroup(
            AddressPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addressPane, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        shoppingPane.addTab("Mailling Label ", AddressPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shoppingPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(shoppingPane, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String item = orderSpinner.getValue().toString().trim();
        
   int cost = 0;

switch (item) {
    case "One Set" -> cost = 450;
    case "Custom Only" -> cost = 350;
    case "Dress" -> cost = 250;
    case "Accesories" -> cost = 150;

  
}

itemsOrdered++;
S1 += item + " - " + cost + "\n"; // ← tampilkan item dan cost TANPA $
numberTextField.setText("Items Ordered: " + itemsOrdered);
numberCartField.setText("Items Ordered: " + itemsOrdered);
costTextField.setText("" + cost); // ← hanya angka

totalCost += cost; // ← simpan total cost

    }//GEN-LAST:event_addButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        OrderTextArea.setText(""); 
        itemsOrdered = 0; 
        numberTextField.setText("Items Ordered: 0"); 
        numberCartField.setText("Items Ordered: 0");
        cartTextArea.setText(null); 
        cartCostField.setText(""); 
        AddressTextArea.setText(""); 
        costTextField.setText("0"); // ← reset ke angka nol tanpa simbol

        S1="";

    }//GEN-LAST:event_newButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    int ex=JOptionPane.showConfirmDialog(null, 
        "Are You Sure ? ", 
        "Konfirmasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE); 
    if (ex==0) { 
        dispose();
    }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void shoppingPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_shoppingPaneStateChanged
        // TODO add your handling code here:  
        switch(shoppingPane.getSelectedIndex()){ 
        case 0 -> {
        }
        case 1 -> {
       if (itemsOrdered == 0) {
        JOptionPane.showConfirmDialog(null, "No items have been ordered.", "Error",
        JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        shoppingPane.setSelectedIndex(0);
       } else {
        cartTextArea.setText(S1);
        cartCostField.setText("" + totalCost); // ← hanya angka total cost
      }
        }
         case 2 -> {
             // establish address and show label form
             if (OrderTextArea.getText().equals(""))
             {
                 JOptionPane.showConfirmDialog(null,
                         "Address is blank.", "Error",
                         JOptionPane.DEFAULT_OPTION,
                         JOptionPane.ERROR_MESSAGE);
                 shoppingPane.setSelectedIndex(0);
             }
             else
             {
                 
//form label
    AddressTextArea.setText("""
                            My Company
                            My Address
                            My City, State, Zip
                            
                            
                            """ + OrderTextArea.getText()); }
        } 
             
    }                                       
          
    }//GEN-LAST:event_shoppingPaneStateChanged

    private void costTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costTextFieldActionPerformed
        // TODO add your handling code here:
      costTextField.setText("Total Cost: $" + totalCost);

    }//GEN-LAST:event_costTextFieldActionPerformed

    private void cartCostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartCostFieldActionPerformed
        // TODO add your handling code here:
     cartCostField.setText("Total Cost: $" + totalCost);

    }//GEN-LAST:event_cartCostFieldActionPerformed

    private void numberCartFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberCartFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_numberCartFieldActionPerformed

    private void numberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_numberTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressPane;
    private javax.swing.JTextArea AddressTextArea;
    private javax.swing.JPanel CartPanel;
    private java.awt.TextArea OrderTextArea;
    private javax.swing.JButton addButton;
    private javax.swing.JScrollPane addressPane;
    private javax.swing.JTextField cartCostField;
    private javax.swing.JScrollPane cartPane;
    private javax.swing.JTextArea cartTextArea;
    private javax.swing.JTextField costTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField numberCartField;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JSpinner orderSpinner;
    private javax.swing.JTabbedPane shoppingPane;
    // End of variables declaration//GEN-END:variables
}
